[package]
name = "ldap-studio-core"
version = "0.0.2"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]
name = "ldap_studio_core"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
uniffi = { version = "0.32", features = ["cli", "tokio"] }
ldap3 = { version = "0.11", default-features = false, features = ["tls-native"] }
tokio = { version = "1", features = ["rt-multi-thread", "time"] }
thiserror = "2"
base64 = "0.22"
