//
//  SetPasswordSheet.swift
//  ldap-studio
//

import SwiftUI

/// A small form for setting `userPassword` — its own sheet rather than an
/// `.alert()`, same reason as `AddAttributeSheet`: `.alert()` on macOS can
/// only host `TextField`/`SecureField`/`Button`, nothing with a `Picker`.
struct SetPasswordSheet: View {
    let onSet: (_ plaintext: String, _ scheme: PasswordScheme) -> Void

    @Environment(\.dismiss) private var dismiss
    @State private var newPassword = ""
    @State private var confirmPassword = ""
    @State private var scheme: PasswordScheme = .pbkdf2Sha512

    private var isValid: Bool {
        !newPassword.isEmpty && newPassword == confirmPassword
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            Text("Set Password")
                .font(.headline)
                .padding()

            Divider()

            VStack(alignment: .leading, spacing: 12) {
                VStack(alignment: .leading, spacing: 4) {
                    Text("New Password")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    SecureField("New Password", text: $newPassword)
                        .textFieldStyle(.roundedBorder)
                }
                VStack(alignment: .leading, spacing: 4) {
                    Text("Confirm Password")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    SecureField("Confirm Password", text: $confirmPassword)
                        .textFieldStyle(.roundedBorder)
                }
                VStack(alignment: .leading, spacing: 4) {
                    Text("Hashing Algorithm")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    Picker("", selection: $scheme) {
                        ForEach(PasswordScheme.allCases, id: \.self) { option in
                            Text(option.displayName).tag(option)
                        }
                    }
                    .labelsHidden()
                }
            }
            .padding()

            Divider()

            HStack {
                Spacer()
                Button("Cancel") {
                    dismiss()
                }
                .keyboardShortcut(.cancelAction)

                Button("Set") {
                    onSet(newPassword, scheme)
                    dismiss()
                }
                .keyboardShortcut(.defaultAction)
                .buttonStyle(.borderedProminent)
                .disabled(!isValid)
            }
            .padding()
        }
        .frame(width: 380)
    }
}

/// Display labels and LDAP scheme tags for the picker above. `PasswordScheme`
/// itself is generated by uniffi from `core/src/password.rs`, so this stays
/// a separate extension rather than editing the generated file.
extension PasswordScheme: CaseIterable {
    public static var allCases: [PasswordScheme] {
        [.pbkdf2Sha512, .unixCrypt, .md5Crypt, .md5, .sha1, .smd5, .ssha, .sha256Crypt, .sha512Crypt]
    }

    var displayName: String {
        switch self {
        case .pbkdf2Sha512: "PBKDF2-SHA512"
        case .unixCrypt: "Unix Crypt"
        case .md5Crypt: "MD5 Crypt"
        case .md5: "MD5"
        case .sha1: "SHA1"
        case .smd5: "SMD5"
        case .ssha: "SSHA"
        case .sha256Crypt: "SHA-256 Crypt"
        case .sha512Crypt: "SHA-512 Crypt"
        }
    }
}

#Preview {
    SetPasswordSheet { _, _ in }
}
